In [7]:
from glob import glob
import pandas as pd
import numpy as np

In [15]:
REGIONS = ["merseyside", "metropolitan", "thames-valley", "west-midlands"]

all_dfs = list()

for region in REGIONS:
    files = glob(f"./*/*/*{region}-street.csv")

    dfs = list()
    for file in files:
        df = pd.read_csv(file)
        dfs.append(df)

    final_df = pd.concat(dfs)
    all_dfs.append(final_df)

display(all_dfs[0].head(), all_dfs[1].head(), all_dfs[2].head(), all_dfs[3].head())

,Crime ID,Month,Reported by,Falls within,Longitude,Latitude,Location,LSOA code,LSOA name,Crime type,Last outcome category,Context
0,2924710b611d2729b431c9757dc8a59b493099db0cdff3...,2024-01,Merseyside Police,Merseyside Police,-2.746819,53.389101,On or near Further/Higher Educational Building,E01012393,Halton 001B,Violence and sexual offences,Unable to prosecute suspect,NaN
1,e7a9106786b1bfe528c102865a0c037b048783a1957b4a...,2024-01,Merseyside Police,Merseyside Police,-2.746819,53.389101,On or near Further/Higher Educational Building,E01012393,Halton 001B,Violence and sexual offences,Unable to prosecute suspect,NaN
2,d46a9cbc559c43816e51d226bf804565ed477011c4faa8...,2024-01,Merseyside Police,Merseyside Police,-2.746819,53.389101,On or near Further/Higher Educational Building,E01012393,Halton 001B,Violence and sexual offences,Unable to prosecute suspect,NaN
3,d4d0e467a342f73aab198be05801aab58d81a29b797751...,2024-01,Merseyside Police,Merseyside Police,-2.746819,53.389101,On or near Further/Higher Educational Building,E01012393,Halton 001B,Violence and sexual offences,Unable to prosecute suspect,NaN
4,c37473887fae15811f36926c98ef841ae09f56694c9904...,2024-01,Merseyside Police,Merseyside Police,-2.872892,53.488785,On or near Brook Hey Drive,E01006448,Knowsley 001A,Drugs,Further action is not in the public interest,NaN

,Crime ID,Month,Reported by,Falls within,Longitude,Latitude,Location,LSOA code,LSOA name,Crime type,Last outcome category,Context
0,e5b3ed0375b796067eb668f37a18094cce300bdbd5446c...,2024-01,Metropolitan Police Service,Metropolitan Police Service,-0.552328,50.853155,On or near Queen Street,E01031392,Arun 001C,Other theft,Unable to prosecute suspect,NaN
1,d5d46efe4a74b2fdf87f28f7c89c4d7534c80d4150f58f...,2024-01,Metropolitan Police Service,Metropolitan Police Service,-0.666558,50.848940,On or near Northfields Lane,E01031396,Arun 003D,Violence and sexual offences,Status update unavailable,NaN
2,8ee491f5ebeda54bda879fed602d2f308bfd8abf4b59f7...,2024-01,Metropolitan Police Service,Metropolitan Police Service,-0.657460,50.787270,On or near Kingsmead,E01031419,Arun 015C,Violence and sexual offences,Status update unavailable,NaN
3,318e91d9bd9ad081bb348b8c743236365c9178eb60229d...,2024-01,Metropolitan Police Service,Metropolitan Police Service,0.876815,51.147655,On or near Parking Area,E01034986,Ashford 005G,Violence and sexual offences,Status update unavailable,NaN
4,8ec949bf76f02215ad73b489ff502ab32101b0834b49fc...,2024-01,Metropolitan Police Service,Metropolitan Police Service,0.884060,51.110654,On or near Southdown Close,E01034989,Ashford 010G,Violence and sexual offences,Status update unavailable,NaN

,Crime ID,Month,Reported by,Falls within,Longitude,Latitude,Location,LSOA code,LSOA name,Crime type,Last outcome category,Context
0,d7654f1ba479644077c254538a4c4f12ab39f5341fae84...,2024-01,Thames Valley Police,Thames Valley Police,-0.692549,51.452793,On or near Winkfield Lane,E01016252,Bracknell Forest 001C,Criminal damage and arson,Unable to prosecute suspect,NaN
1,0a2cc51135bfff5c41c6d063e670555e5afc292ec00780...,2024-01,Thames Valley Police,Thames Valley Police,-0.658082,51.438484,On or near Park/Open Space,E01016252,Bracknell Forest 001C,Public order,Investigation complete; no suspect identified,NaN
2,26bfc1bb14564f58085e18da2a6f9822efb49c8627bfe3...,2024-01,Thames Valley Police,Thames Valley Police,-0.677236,51.436336,On or near Lovel Road,E01016252,Bracknell Forest 001C,Vehicle crime,Investigation complete; no suspect identified,NaN
3,f9cce6ed554d064626a11c41c5e2edd0467174f5ae397b...,2024-01,Thames Valley Police,Thames Valley Police,-0.674292,51.447112,On or near Crouch Lane,E01016252,Bracknell Forest 001C,Violence and sexual offences,Action to be taken by another organisation,NaN
4,37116d29794088cdcefa2ff08f6cfd2027a8af918c13ad...,2024-01,Thames Valley Police,Thames Valley Police,-0.677236,51.436336,On or near Lovel Road,E01016252,Bracknell Forest 001C,Violence and sexual offences,Unable to prosecute suspect,NaN

,Crime ID,Month,Reported by,Falls within,Longitude,Latitude,Location,LSOA code,LSOA name,Crime type,Last outcome category,Context
0,NaN,2024-01,West Midlands Police,West Midlands Police,-1.849790,52.590937,On or near Walsall Road,E01009417,Birmingham 001A,Anti-social behaviour,NaN,NaN
1,NaN,2024-01,West Midlands Police,West Midlands Police,-1.840582,52.598279,On or near Badgers Bank Road,E01009418,Birmingham 001B,Anti-social behaviour,NaN,NaN
2,08fcc46d224b1e4f4065b950fa59e5251d51106f3472cd...,2024-01,West Midlands Police,West Midlands Police,-1.840582,52.598279,On or near Badgers Bank Road,E01009418,Birmingham 001B,Vehicle crime,Investigation complete; no suspect identified,NaN
3,5fc5ebcc637a23f9410af6ee90daabdaefed70fd86f93b...,2024-01,West Midlands Police,West Midlands Police,-1.845233,52.593943,On or near Harcourt Drive,E01009418,Birmingham 001B,Violence and sexual offences,Unable to prosecute suspect,NaN
4,5ea6fbc3cd6834f56ba25852736e3e4d53a70163f2a3a3...,2024-01,West Midlands Police,West Midlands Police,-1.839093,52.597818,On or near Byron Court,E01009418,Birmingham 001B,Violence and sexual offences,Unable to prosecute suspect,NaN

In [ ]:
final_df.groupby("Month")["Crime ID"].count()

Month
2024-01    11107
2024-02    10530
2024-03    11367
2024-04    11237
2024-05    12382
2024-06    11554
2024-07    12068
2024-08    11263
2024-09    11103
2024-10    11478
2024-11    11057
2024-12    10515
2025-01     9995
2025-02    10097
2025-03    11849
2025-04    11128
2025-05    12176
2025-06    11800
2025-07    12158
2025-08    12226
2025-09    11566
2025-10    11914
2025-11    11388
2025-12    11094
2026-01    10499
Name: Crime ID, dtype: int64